### ISSUE TITLE
360_day calendar tests

### ISSUE THREAD

**Issue by marev711** [cerfacs-globc/icclim#12]
360_day branch is technically working but further test to verify the implementation independently are needed (as discussed). Could we list the recommended short lists of indices to include for this testing in this issue?

**Comment by MilkaRadojevic** [comment]
Traceback (most recent call last):
  File "./run_icclim413_era20c_v2.py", line 105, in <module>
    callback=callback.defaultCallback,callback_percentage_start_value=0, callback_percentage_total=100)
  File "/scratch/globc/milka/icclim4.1.2/icclim/icclim.py", line 435, in indice
    i2_col_current_tile=i2_col_current_tile)
  File "/scratch/globc/milka/icclim4.1.2/icclim/util/util_nc.py", line 275, in get_values_arr_and_dt_arr
    dt_arr = numpy.array([util_dt.num2date(dt, calend=calend, units=units) for dt in time_arr])
  File "/scratch/globc/milka/icclim4.1.2/icclim/util/util_dt.py", line 147, in num2date
    dt = datetime(dt.year, dt.month, dt.day, dt.hour)
ValueError: day is out of range for month

**Comment by pagecp** [comment]
Tests done and validated. Available in release 4.2.1.

**Comment by MilkaRadojevic** [comment]
Import error for icclim (the same as for icclim_360days brunch):
 import icclim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "icclim/__init__.py", line 1, in <module>
    from icclim import *
  File "icclim/icclim.py", line 23, in <module>
    import calc_percentiles
  File "icclim/calc_percentiles.py", line 15, in <module>
    import util.calc as calc
  File "icclim/util/calc.py", line 13, in <module>
    import util_dt
  File "icclim/util/util_dt.py", line 15, in <module>
    from icclim_exceptions import *
ImportError: No module named icclim_exceptions

**Comment by pagecp** [comment]
Start with a fresh directory and clone the master 4.2.2. The icclim_exceptions are new files that can be seen here:
https://github.com/cerfacs-globc/icclim/tree/master/icclim
I suspect that the switch to other branch or master did not work or was not in a fresh directory.

**Comment by MilkaRadojevic** [comment]
When trying to execute the icclim4.2.2  from the subdirectory icclim:
    import icclim.util.callback as callback #PROGRESS BAR IN %
ImportError: No module named util.callback

**Comment by pagecp** [comment]
icclim_exceptions import fixed in util_dt.py in 4.2.3.

**Comment by MilkaRadojevic** [comment]
The percentage progress bar is printed if the callback parameter is set to a callback function. The default callback functions are defined in:
icclim/util/callback.py

**Comment by MilkaRadojevic** [comment]
Error while reading input with 360 days:
  File "/scratch/globc/milka/icclim-4.2.3/icclim/icclim.py", line 447, in indice
    i2_col_current_tile=i2_col_current_tile)
  File "/scratch/globc/milka/icclim-4.2.3/icclim/util/util_nc.py", line 287, in get_values_arr_and_dt_arr
    indices_subset = util_dt.get_indices_subset(dt_arr, time_range)
  File "/scratch/globc/milka/icclim-4.2.3/icclim/util/util_dt.py", line 291, in get_indices_subset
    raise ValueError(error_msg)
ValueError: Lower limit input to time array is earlier than available time steps, dt1 < dt_arr[0]: 1951-01-01 12:00:00 < 1951-01-01 12:00:00
