### ISSUE TITLE
[icclim4.1.0] KeyError: 'files_years'

### ISSUE THREAD

**Issue by MilkaRadojevic** [cerfacs-globc/icclim#9]
When trying to run icclim4.1.0 the error message appears at line 404 in the icclim.py" (see below). 
Note that icclim4.0.3 does not show this type of error.

It looks like an issue with defining time array. Any thoughts on this? Solution?

[milka@nemoglobc1 icclim-4.1.0]$
CLIMATE INDEX: TX10p
INPUT VARNAME: tasmax
INPUT FILE: /scratch/globc/milka/CLIPC/icclim-4.1.0/cat_tasmax_1d_EUR-11_19890101-20101231_EURO4M_MESANv1.nc
1989-01-01 00:00:00 2010-12-31 00:00:00 1989-01-01 00:00:00 2010-12-31 00:00:00
Loading data: chunk 1/16 ...
Loading data: chunk 2/16 ...
Traceback (most recent call last):
  File "./run_icclim4.py", line 116, in <module>
    icclim.indice(indice_name=Indice_Name, in_files=File_InVar, var_name=Name_InVar, time_range=[dt1, dt2], base_period_time_range=[ref_dt1, ref_dt2], out_unit='days', out_file=Indice_OutFile, transfer_limit_Mbytes=500, callback=callback.defaultCallback2)
  File "/scratch/globc/milka/CLIPC/icclim-4.1.0/icclim/icclim.py", line 404, in indice
    nc = MFDataset(VARS[v]['files_years'].keys(), 'r', aggdim=dim_name) # VARS[v]['files_years'].keys(): files of current variable
KeyError: 'files_years'

**Comment by MilkaRadojevic** [comment]
Solution found:
---------------------------------------------------------------------------------------------------------------------------------------------
ICCLIM 4.1.0 supports ONLY date in form YYYY-MM-DD while the previous versions require date in the form of YYYY-MM-DD HH:MM:SS.
----------------------------------------------------------------------------------------------------------------------------------------------
For example
in icclim4.1.0: dt1 = datetime(1980,01,01)
in icclim4.0 and older: dt1= datetime.datetime(1980,01,01) 

Note:
This information should be corrected in the ICCLIM 4.1.0 documentation.
